brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [

    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("todo_list_list")),
        name="home",
    ),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoListDetailView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return str(self.task)

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from todos.models import TodoList

# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
            </div>
            <table>
                <thread>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
                </thread>
                <tbody>
                    {% for todo in todolist_list %}
                        <tr>
                            <td>{{ todo.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'todo_list_detail'  %}">Details</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Lists</h1>
            </div>
            <table>
                <thread>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
                </thread>
                <tbody>
                    {% for todo in todolist_list %}
                        <tr>
                            <td>{{ todo.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>